### ISSUE TITLE
Request: PSX/Saturn/PC-FX/TurboGrafx CD using Mednafen

### ISSUE THREAD

**Issue by arnoldsecret** [quinton-ashley/nostlan#15]
Databases for their Redump sets are available for these consoles.

**Comment by quinton-ashley** [comment]
What's a Redump set?  How do I get the databases?

**Comment by arnoldsecret** [comment]
redump.org/downloads

**Comment by quinton-ashley** [comment]
I need a way to identify the games without using the game file names.  Are there tools that can do that for these games?

**Comment by quinton-ashley** [comment]
no response, closing this issue
