### ISSUE TITLE
Change skin ?

### ISSUE THREAD

**Issue by azoreseuropa** [quinton-ashley/nostlan#17]
Good job but I dont liked SNES skin. Is there a way I can change it to Europe SNES skin ? I hate American SNES purple skin. Ugh!

**Comment by quinton-ashley** [comment]
Check out this wiki page I just made:
<https://github.com/quinton-ashley/nostlan/wiki/Change-Theme>

I'll give you this month's Patreon password for free if you'd like!  Email me qashto@gmail.com
