### ISSUE TITLE
XBOX360 Games Scraping for HALO 3 when halo3 files are not present in folder

### ISSUE THREAD

**Issue by Merith-TK** [quinton-ashley/nostlan#21]
![image](https://user-images.githubusercontent.com/10422110/86868120-fbc07200-c088-11ea-87e4-a6214069cc33.png)
The Halo 3 game is not present in this folder which is where i have it configured to find games

**Comment by Merith-TK** [comment]
In this list, we have 
Skyrim (+dlc)
Bakugan Defenders of the Core
and HAWKX2

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/86868907-7342d100-c08a-11ea-86b8-58e9cf57ac93.png)

**Comment by quinton-ashley** [comment]
Hi thanks for reporting this I will look into the problem.  Halo 3 is the default game box art for the xbox 360 that's why it's being loaded.

**Comment by Merith-TK** [comment]
Yeah a fix would be nice, because while i physically own a copy of the game, the disc is damaged so i cant dump it myself, nor have i been able to find a dump in the normal xenia format

**Comment by Merith-TK** [comment]
My Point
![](https://cdn.discordapp.com/attachments/309008096800276490/730241340885041202/20200707_185353.jpg)

**Comment by quinton-ashley** [comment]
This issue should be fixed now, lmk!

**Comment by quinton-ashley** [comment]
That's not necessary, 1.11.0 should work.  I had to upload the default image to nostlan-img.
