### ISSUE TITLE
AppImage stuck on "starting Nostlan!"

### ISSUE THREAD

**Issue by bombatomba77** [quinton-ashley/nostlan#23]
Tried on Manjaro, Ubuntu, and Mint all with same issue.  Executing opens full screen with "starting Nostlan!" but nothing else.  I can mouse around and click on the four corners but it does nothing I can see.  I've let it sit for about an hour (on accident) and it does nothing new.  Running from command line produces the following output:

{
  arg: '{"_":["/tmp/.mount_nostlasXQKpC/nostlan"],"__root":"/tmp/.mount_nostlasXQKpC/resources/app.asar","node_modules":"/tmp/.mount_nostlasXQKpC/resources/app.asar/node_modules","electron":true}',
  node_modules: '/tmp/.mount_nostlasXQKpC/resources/app.asar/node_modules'
}
(node:15928) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.

**Comment by quinton-ashley** [comment]
Did you install libvips ?
Linux users must install libvips (a fast image processing library)

**Comment by bombatomba77** [comment]
Installed libvips42 and libvips-dev (just in case).  I actually tried this with several past versions of Nostlan just in case, and all do the same thing.

**Comment by quinton-ashley** [comment]
Well there was a bug in Nostlan v1.13.0 that prevented Nostlan from starting in some cases, more info on Discord.
https://discord.com/channels/698656653633126441/698656654081785938

**Comment by quinton-ashley** [comment]
Can you confirm that v1.14.x works on your computer?
