### ISSUE TITLE
Loading nostlan stuck 

### ISSUE THREAD

**Issue by Blinkingcape8** [quinton-ashley/nostlan#25]
When I started up Nostlan  everything looked like it was starting fine but I am currently stuck at Loading "additional images" and "discSleev" what would I need to do, or what information would you need from me

**Comment by quinton-ashley** [comment]
oh no! Yes I need some more info. Open the dev tools with ctrl+shift+i or ctrl+alt+i and take a screenshoot of the console tab and post it

**Comment by Blinkingcape8** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/71569565/93694397-f8a62100-fad0-11ea-8086-8b090bbbb99b.png)
![Screenshot (2)](https://user-images.githubusercontent.com/71569565/93694400-fba11180-fad0-11ea-97bd-f9ec72bd5350.png)

**Comment by Blinkingcape8** [comment]
hopefully that helps if you need something more, Will do as requested

**Comment by quinton-ashley** [comment]
Thanks! Your settings in your preferences file  `emu/nostlan/_usr/prefs.json`must've got erased somehow. You can erase the file and setup Nostlan in the app or if you know how to edit json fill in the nlaDir property to be your

**Comment by Blinkingcape8** [comment]
thank you will do
