### ISSUE TITLE
How do you go back to the Systems menu?

### ISSUE THREAD

**Issue by BojayB** [quinton-ashley/nostlan#28]
Im not sure what you would call it, but the main menu where it shows all of the systems you can emulate from, the different TYPES of games. when I boot Nostlan, it takes me straight to the arcade menu, and I dont see a button to go back to choose a different menu.

**Comment by quinton-ashley** [comment]
Select "Sys" (short for systems) from the game library view overlay.

https://github.com/quinton-ashley/nostlan/wiki/How-to-use-Nostlan

**Comment by BojayB** [comment]
I only asked because I don't have the "Sys" button because my library hasn't had the chance to load yet.
