### ISSUE TITLE
macOS - The app can't be opened

### ISSUE THREAD

**Issue by nicolasonline** [quinton-ashley/nostlan#33]
Hello,

I'm on macOS 10.15.7 and just downloaded the latest release 1.20.5 zip for macOS. I did some digging and saw that there was an issue opened a while back regarding this issue that had been resolved. This is not the "unidentified developer" issue as it does not appear in the Security & Privacy tab of system preferences to Open Anyway. Is there something I'm missing, thanks a lot.

**Comment by quinton-ashley** [comment]
I can't get the codesiging to work. I will try to fix this asap.

**Comment by quinton-ashley** [comment]
I think I fixed it! Download 1.20.6 and lmk

**Comment by nicolasonline** [comment]
1.20.7 worked thanks a lot! Looking forward to trying it out
