### ISSUE TITLE
yuzu Linux

### ISSUE THREAD

**Issue by varlesh** [quinton-ashley/nostlan#36]
directories on Linux not right.
Yuzu create `~/.local/share/yuzu/`, but on Nostlan used `~/.local/share/yuzu-emu`:
https://github.com/quinton-ashley/nostlan/blob/master/core/saves.js#L98
Also yuzu provide for linux as yuzu-*.AppImage, but Nostlan used:
https://github.com/quinton-ashley/nostlan/blob/master/prefs/prefsDefaults.json#L440

Also why needed wine?
https://github.com/quinton-ashley/nostlan/blob/master/prefs/prefsDefaults.json#L444

Yuzu native app for linux

**Comment by varlesh** [comment]
For example latest release for linux:
https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-583/yuzu-20210405-483bb6472.AppImage

**Comment by quinton-ashley** [comment]
Thank you for letting me know! I'll fix this asap

**Comment by quinton-ashley** [comment]
fixed in v1.20.16 lmk if it works for you!
