### ISSUE TITLE
Hebrew Translation Issues

### ISSUE THREAD

**Issue by elBandoler** [quinton-ashley/nostlan#42]
I have decided to test the Hebrew translation and check if there were any bugs when using it. Found some small issues:

- The term "Hebrew" always refers to the modern, Israeli dialect of that language. Other dialects are basically dead for centuries at this point, and are mutually intelligible anyways, so there is no need to add "(modern)" in the language selection screen.

- Another issue I found is the RTL writing.
![image](https://user-images.githubusercontent.com/10284630/120102253-cadea500-c152-11eb-8b46-38fb52c58b70.png)
This phrase (the first button of the Nostlan Setup) should look like this:
![image](https://user-images.githubusercontent.com/10284630/120102280-e8137380-c152-11eb-98c3-38705320d033.png)
This issue is repeated in each and every occurance of text in both Hebrew and English in the same sentence, for example:
![image](https://user-images.githubusercontent.com/10284630/120102349-3759a400-c153-11eb-8364-adcc33811c1b.png)
Which should look like this:
![image](https://user-images.githubusercontent.com/10284630/120102359-42accf80-c153-11eb-9c45-f483e2f01ea4.png)
And sometimes it mixes up the sentences, like here: 
![image](https://user-images.githubusercontent.com/10284630/120102386-640dbb80-c153-11eb-9145-89b1ad60c223.png)
which **literally** translates to: 
```
game yet you might want GBA if you have no .gba :game files must end with the extension
emulator software first mGBA install the
```
- The font is very simple (and tbf, kinda ugly for Hebrew). I recommend using a Google Fonts one, if possible. Otherwise, there's a ton of free Hebrew fonts, I could search for a nice one later. Yes, Hebrew is so weird it requires its own font 😐 

I found no other issues currently 😄

**Comment by quinton-ashley** [comment]
Okay I will remove the (modern) that's just how the language package I'm using labelled it.

Interesting, now I get what you meant by right to left! I'll swap the text around.

**Comment by quinton-ashley** [comment]
The top two look just like how you have it in the file. You'll need change it in the language file.

As for the "No games found" message, that's a different issue cause Nostlan interjects information into that. I think swapping the parts around will work. So if a message has two parts "msg0_0" and "msg0_1", parts are denoted by the "_" make the first part go in 1 and the second part in 0.

**Comment by elBandoler** [comment]
Greetings!
I've started college and barely got any available time.
Unfortunately, this means I'm not sure if and when I'll be able to complete the required fixes.

In regards to the font, I believe the fonts Assistant and Heebo from the Google Fonts repository would be the best choice.

**Comment by quinton-ashley** [comment]
Sorry for the late response. Well thank you for what you did contribute! I will take a look at those fonts.
