### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by bleuge** [quinton-ashley/nostlan#43]
Many of the launchers you had on the page that explains differences with other launches, you forgot to say that emulationstation, pegasus, etc... are completely themeable, if you don't like metadata you can use other themes with full-screen images or whatever you like. So I don't think  your comparison is fair.

Anyway, I'll test it, always happy to test new frontends.

I think you could improve adoption if for example I could point nostlan to a emulationstation instalation (retropie, configured retroarch,etc), and gamelists and media could be plain imported and used. Many people have this kind of setup. And autoconfiguring via retroarch cores (nostlan detect the cores so it knows what can be emulated and how)

Thanks for your efforts!

**Comment by quinton-ashley** [comment]
I'm only comparing how they look out of the box, Nostlan is fully customizable too but most users aren't going to be putting the work in to change it. I will add that they are customizable but for the average user this doesn't matter that much and is over-emphasized by their developers imo.

Thanks! Good ideas, I'll look into how to make Nostlan compatible with other setups.
