### ISSUE TITLE
Add more options for install on Linux

### ISSUE THREAD

**Issue by varlesh** [quinton-ashley/nostlan#45]
Hi. It's possible add support flatpak exec for Linux?
Because mostly emulators distributed as flatpak:

- dolphin - flatpak, snap (not actual)
- yuzu - flatpak, appimage
- ryujinx - appimage
- citra - flatpak, snap
- snes9x - flatpak
- melonDS - flatpak, snap
- mgba - flatpak, snap
- pcsx2 - flatpak
- rpcs3 -  flatpak, snap
- xenia - compile from sources

It's not big problem for me, i can create symlinks:
`ln -s /var/lib/flatpak/app/org.DolphinEmu.dolphin-emu/x86_64/stable/active/export/bin/org.DolphinEmu.dolphin-emu ~/.local/bin/dolphin-emu`
It's only not comphortable ))
Or maybe better doing configuration file for exec path emulators?

**Comment by varlesh** [comment]
oops... sorry. Nostlan now have installation. Fine!!!

**Comment by quinton-ashley** [comment]
If you go to the Nostlan menu and edit settings you can make your own launch commands in the `prefs.json` file too. I will add some more options for installing on linux in the future!
