### ISSUE TITLE
fullscreenKeyCombo not working for some emulators on Linux

### ISSUE THREAD

**Issue by varlesh** [quinton-ashley/nostlan#47]
fullscreenKeyCombo not worked on Yuzu & Dolphin
```
	"dolphin": {
		"app": "org.DolphinEmu.dolphin-emu",
		"cmd": [
			"flatpak",
			"run",
			"${app}",
			"-e",
			"${game}"
		],
		"fullscreenKeyCombo": [
			"f11"
		]
	},
	"yuzu": {
		"cmd": [
			"flatpak",
			"run",
			"${app}",
			"${game}"
		],
		"fullscreenKeyCombo": [
			"f11"
		],
		"app": "org.yuzu_emu.yuzu"
	},
```
With Citra worked

**Comment by varlesh** [comment]
with Ryujinx not worked too.
Maybe need added little sleep time for run fullscreenKeyCombo? I think it start before then emulator run

**Comment by quinton-ashley** [comment]
Which OS are you on?

**Comment by varlesh** [comment]
KDE Neon (Ubuntu 20.04)

**Comment by quinton-ashley** [comment]
Is the full screen key incorrect for those emulators on Linux or do you think it's just doing it at the wrong time?

**Comment by varlesh** [comment]
@quinton-ashley F11 not needed anymore:

- Yuzu need run with option `-f -g`
- Ryujinx need change value on **Config.json** to `"start_fullscreen": true,`
- Dolphin need run with option `--config "Dolphin.Display.Fullscreen=True"`
- Citra need change value on **qt-config.ini** to:

```
fullscreen=true
fullscreen\default=false
```

**Comment by varlesh** [comment]
> Is the full screen key incorrect for those emulators on Linux or do you think it's just doing it at the wrong time?

All keys use only F11 (i check it). Yes it's doing wrong time - before starting the emulator (i see how change fullscreen state on Nostlan)

**Comment by quinton-ashley** [comment]
thanks for that info! I'll update the cmd settings in `core/emulators.js`

**Comment by quinton-ashley** [comment]
@varlesh Where is the qt-config.ini for Citra?

**Comment by varlesh** [comment]
Fullscreen commands & configs:

Citra flatpak:
**fullscreen=true
fullscreen\default=false**
`~/.var/app/org.citra_emu.citra/config/citra-emu/qt-config.ini`

Ryujinx (not have flatpak version):
**"start_fullscreen": true,**
`~/.config/Ryujinx/Config.json`

PCSX2 flatpak:
**DefaultToFullscreen=enabled**
`~/.var/app/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_ui.ini`

PPSSPP flatpak:
**FullScreen = True**
`~/.var/app/org.ppsspp.PPSSPP/config/ppsspp/PSP/SYSTEM/ppsspp.ini`

Yuzu flatpak:
`flatpak run org.yuzu_emu.yuzu -f -g`

Dolphin flatpak:
`flatpak run org.DolphinEmu.dolphin-emu --config "Dolphin.Display.Fullscreen=True"`

Only melonDS not have this function, but available fixed fork for that with this artiifacts:
https://github.com/Arisotura/melonDS/issues/237#issuecomment-889533716

other emulators have not been investigated

**Comment by quinton-ashley** [comment]
Thanks for this research!! I'll implement these in the next version of Nostlan.

**Comment by varlesh** [comment]
**upd**
PCSX2 have command line option:
`flatpak run net.pcsx2.PCSX2 --fullscreen --nogui`

**Comment by varlesh** [comment]
RPCS3:
**Start games in fullscreen mode: true**
`~/.var/app/net.rpcs3.RPCS3/config/rpcs3/config.yml`
