### ISSUE TITLE
Add Support for non Flatpak Emulators on Linux

### ISSUE THREAD

**Issue by Fancy2209** [quinton-ashley/nostlan#52]
I personally only use Snes9x and Dolphin as flatpaks and the rest I just use non flatpaks
I tried adding melonDS for example but it was still ran as a flatpak
Is this not integrated or did I just not find a way to run melonDS, PCSX2 and mGBA and meson from my path executables?
Oh also yes Meson does run on Linux trough mono, just realized there is no setup option for that one on linux

**Comment by quinton-ashley** [comment]
You can edit app paths and launch commands in your user preferences file.
https://github.com/quinton-ashley/nostlan/wiki/User-Preferences
