### ISSUE TITLE
macOS build shadowbanned by Apple? Nostlan has been incorrectly flagged as malware

### ISSUE THREAD

**Issue by mspacemedia** [quinton-ashley/nostlan#55]
Sorry, just read on gitters that the malware issue should be fixed - I'm running Big Sur fully updated and this build still reports as malware and closes instantly.

**Comment by quinton-ashley** [comment]
ah dang. Thanks for letting me know. Can you send a picture of the warning?

**Comment by quinton-ashley** [comment]
Please try the latest build:
https://github.com/quinton-ashley/nostlan/releases/tag/beta-1.23.x

**Comment by mspacemedia** [comment]
Sorry never got round to the image - here you go taken from 1.23

<img width="886" alt="Screenshot 2021-11-24 at 22 44 00" src="https://user-images.githubusercontent.com/858675/143322131-2a410f52-f1bf-4cdb-b65c-5a2186b71c17.png">

And what are the chances of supporting PCSX2 on MacOS using this build: 

https://github.com/tellowkrinkle/pcsx2/releases/tag/macos-20211121

**Comment by quinton-ashley** [comment]
Apple has possibly shadowbanned the app. There's nothing wrong with the codesigning on my end. Try the new v1.23 build and if it doesn't work you can contact Apple. There's nothing more I can do.

**Comment by quinton-ashley** [comment]
nevermind it was just a problem with `electron-builder`, problem seems to have been solved!
