### ISSUE TITLE
Latest Mac app executable crashes immediately

### ISSUE THREAD

**Issue by tonywoode** [quinton-ashley/nostlan#56]
On Catalina on mac 10.15.7. I think the salient item from the report is:  DYLD, [0x5] Code Signature
Here's the relevant part of the trace:

```
Process:               nostlan [27283]
Path:                  /Users/USER/Desktop/nostlan.app/Contents/MacOS/nostlan
Identifier:            com.qashto.nostlan
Version:               1.24.4 (1.24.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nostlan [27283]

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Desktop/nostlan.app/Contents/MacOS/nostlan
  Reason: no suitable image found.  Did find:
	/Users/me/Desktop/nostlan.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/Users/me/Desktop/nostlan.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

	/Users/me/Desktop/nostlan.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
```

**Comment by quinton-ashley** [comment]
I don't know how to fix this. When I code sign the app build with my Apple ID and verify it, it looks like everything is fine. Even when I run the verification check on another mac it was fine but it still crashes immediately.

**Comment by tonywoode** [comment]
thanks. Guess you've tried this (I see you run `codesign` in `package.json`, not sure what it is, but suggestion from [here](https://stackoverflow.com/questions/36402071/submitting-electron-app-to-mac-app-store-error-invalid-signature):

https://github.com/electron/osx-sign

Googling the issue does seem to come up with several frustrations (in particular [this washing of hands](https://developer.apple.com/forums/thread/121422), though the idea of deleting and remaking your developer account (which I guess results in producing a new ID or similar) crops up several times, the suggestion is that free dev accounts are time limited or similar

**Comment by quinton-ashley** [comment]
thanks for all these leads! I definitely want to fix this now that I understand the problem better.

I use electron-builder for building the app releases and I'm going to try the new version out to see if they fixed it. I'm going to create a separate profile on my mac so I can test the builds now that I know the scope of the problem (it's affecting all macOS users on the latest versions of macOS)

If that doesn't work then I'll try electron-packager

**Comment by tonywoode** [comment]
thanks so much! I'll try to do any testing you need just ping! I'd be interested to understand more of the issues here, since MacOS is notoriously finicky and brittle with non-apple-ecosystem apps, yet what's the point of cross-platform development if you can't include macos as a platform witout 10x the trouble of windows and *nix!

**Comment by quinton-ashley** [comment]
> thanks. Guess you've tried this: (I see you run `codesign` in `package.json`, not sure what it is

codesign is a command line tool used to verify if an app is signed properly but apparently it doesn't work on the latest versions of macOS

**Comment by quinton-ashley** [comment]
@tonywoode Does the new version of Nostlan work?

**Comment by quinton-ashley** [comment]
Yay!! I wanted to just wait a bit and see if the developers of `electron-builder` would fix the problems and it seems they did!
