### ISSUE TITLE
Add Sinclair ZX Spectrum formats support

### ISSUE THREAD

**Issue by Korb** [quinton-ashley/nostlan#65]
1. `.air` (RealSpec)
2. `.dck` (Warajevo)
3. `.dsk`
4. `.fdi`
5. `.hdf` (RealSpec and Fuse)
6. `.img`
7. `.mdr`
8. `.mgt`
9. `.pok` (SGD)
10. `.rzx`
11. `.slt`
12. `.sna`
13. `.szx` (Spectaculator)
14. `.tap`
15. `.trd`
16. `.tzx`
17. `.z80`

**Comment by quinton-ashley** [comment]
Sorry, I'm not planning on adding ZX Spectrum support to Nostlan
