### ISSUE TITLE
Nostlan on macOS root dir permission error

### ISSUE THREAD

**Issue by AwesomeCoder412412** [quinton-ashley/nostlan#9]
When I first started up bottlenose and it asked me for my dolphin wii game directory, I created a folder and put in one of my games to test it out. I waited and waited, but it stayed on that screen. It wasn't frozen, and strangely enough, I couldn't minimize it. I quit bottlenose, restarted my mac, and checked to make sure it was updated then tried again and the same thing happened. How do I fix this?  ( have a macbook pro with touchbar. The video of the error is in the zip file. I also included pictures of where the folder was.)
[problem.mov.zip](https://github.com/quinton-ashley/bottlenose/files/3655295/problem.mov.zip)
<img width="636" alt="Screen Shot 2019-09-25 at 5 09 52 PM" src="https://user-images.githubusercontent.com/44704454/65648734-5c7a3480-dfb8-11e9-9ed0-918c4fbd3eaf.png">
<img width="636" alt="Screen Shot 2019-09-25 at 5 09 52 PM" src="https://user-images.githubusercontent.com/44704454/65648752-6d2aaa80-dfb8-11e9-8dcd-ca1131e89c9a.png">

**Comment by quinton-ashley** [comment]
Sorry about that.  When you load the app use the keyboard shortcut "command+option+i".  Send me a screenshot of the console log.  Also in the bottlenose user folder there might be an error log file.

**Comment by AwesomeCoder412412** [comment]
<img width="1440" alt="Screen Shot 2019-09-26 at 3 58 48 PM" src="https://user-images.githubusercontent.com/44704454/65730585-23ed6000-e077-11e9-9f79-472cd7e99130.png">
<img width="1440" alt="Screen Shot 2019-09-26 at 3 57 29 PM" src="https://user-images.githubusercontent.com/44704454/65730591-26e85080-e077-11e9-85a6-b1cf3f827e1e.png">

**Comment by AwesomeCoder412412** [comment]
Do these help?(and also where do you find the console log?)

**Comment by quinton-ashley** [comment]
Sorry you can't have your games in `/Applications` because Bottlenose (now called Nostlan) will try to make an image directory at your root folder.  I will fix this problem in the next release.  For now you can just use the default location for games in `~/Documents/emu/Dolphin/GAMES` and the app should work.  You'll need to delete `~/Documents/emu/_usr`

**Comment by AwesomeCoder412412** [comment]
The nGBA emulation page isn't working.
<img width="1440" alt="Screen Shot 2019-09-28 at 7 20 33 AM" src="https://user-images.githubusercontent.com/44704454/65817824-928a0500-e1c0-11e9-86a1-899b45bddd49.png">
when I try clicking on the little metal things, nothing happens, and it thinks crash bandicoot is pokemon fire red.

**Comment by AwesomeCoder412412** [comment]
<img width="1440" alt="Screen Shot 2019-09-28 at 7 24 23 AM" src="https://user-images.githubusercontent.com/44704454/65817864-09bf9900-e1c1-11e9-80a2-d4de7243cb64.png">

**Comment by AwesomeCoder412412** [comment]
I am keeping the game(it's a .sav file) in ~/Documents/emu/mGBA/GAMES

**Comment by quinton-ashley** [comment]
Open the pause menu by clicking on the bottlenose button in the upper right.  Then click "recheck images" let me know if that works.  I think there might be another problem specific to gba too that I will fix in the next version.  Does it work with your other game libraries?

**Comment by quinton-ashley** [comment]
Just uploaded a new version v1.3 try it out.

**Comment by quinton-ashley** [comment]
I actually fixed this in v1.4.2 for real!  The problem was that it was looking for Pokemon Red's box art because it's the default box.
